export const languageNameMap: Record<string, string> = {
  all: 'General Programming',
  js: 'JavaScript',
  py: 'Python',
  go: 'Go',
  rust: 'Rust',
  java: 'Java',
  cpp: 'C++',
  pascal: 'Pascal',
  csharp: 'C#',
  typescript: 'TypeScript',
  swift: 'Swift',
  kotlin: 'Kotlin',
  php: 'PHP',
  ruby: 'Ruby',
  sql: 'SQL',
  dart: 'Dart',
  r: 'R',
  elixir: 'Elixir',
  haskell: 'Haskell',
  lua: 'Lua',
  perl: 'Perl',
  scala: 'Scala',
  bash: 'Bash',
};
